Mapping
dosemu2/dosemu2 pull request #2015
Opened 2023-06-07 17:16 UTC by stsp

This reworks mapfile and makes mremap optional.

2023-06-07 19:30 UTC, stsp commented
Hi Bart, would be good to get a review
on this. Also I'd need your ack on the
copyright updates.

2023-06-08 01:31 UTC, bartoldeman requested changes
Certainly simplifies things to have one fd per alloc_mapping, but if the goal is to only make mremap optional a much smaller patch would do (much like in just the first commits of your patchset)

I'd personally split it in two PRs.

2023-06-08 01:31 UTC, bartoldeman commented on src/arch/linux/mapping/mapfile.c
> +      munmap(addr, oldsize);
When you do this aren't you supposed to memcpy from old to new as well?
Or you could simply refuse to do anything here, and return MAP_FAILED, as mapping.c can take care of it (you just declare it non-expandable like in mapshm.c).

2023-06-08 01:34 UTC, bartoldeman commented
Copyright should be ok, if very little is in common with how it was in 1.1.2 (it looks like that for sure).

2023-06-08 04:59 UTC, stsp commented on src/arch/linux/mapping/mapfile.c
> +      munmap(addr, oldsize);
No, and this is why its a single PR.
I just mmap from the same fd/offs,
so no memcpy() is needed.
Its not possible in the old code, because
there you would mmap the larger chunk
from an entirely different "hole" within
the large swapfile. In which case you
need memcpy(), but here it is entirely
avoided, you do ftruncate() per mapping.
So I really find that technique not only
the simplification, but a step forward.

2023-06-09 06:15 UTC, stsp commented on src/arch/linux/mapping/mapfile.c
> +      munmap(addr, oldsize);
> Or you could simply refuse to do anything here, and return MAP_FAILED, as mapping.c can
> take care of it (you just declare it non-expandable like in mapshm.c).

I think its a deficiency of mremap() to
not being able to expand anonymous shm.
I even sent patches to lkml something like
20 years ago to fix that, but they were
afraid that such things could be exploited
to exhaust shm resources and so on...

So instead of returning MAP_FAILED, we
can as well remove the ashm back-end.

2023-06-09 14:23 UTC, merged